### ISSUE TITLE
can't run simulation example ...!

### ISSUE THREAD

**Issue by aven1** [miquelmartin/Siafu#7]
hi,
I get this error while trying run simulation example...
.
.
.
Starting Siafu...
Exception in thread "Simulation thread" java.lang.RuntimeException: Can't instan
tiate the world model
        at de.nec.nle.siafu.model.World.createPlaces(World.java:926)
        at de.nec.nle.siafu.model.World.<init>(World.java:231)
        at de.nec.nle.siafu.control.Simulation.run(Simulation.java:204)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: class de.ne
c.nle.siafu.testland.WorldModel
        at de.nec.nle.siafu.model.SimulationData.getWorldModelClass(SimulationDa
ta.java:173)
        at de.nec.nle.siafu.model.World.createPlaces(World.java:921)
        ... 3 more
Caused by: java.lang.ClassCastException: class de.nec.nle.siafu.testland.WorldMo
del
        at java.lang.Class.asSubclass(Unknown Source)
        at de.nec.nle.siafu.model.SimulationData.getWorldModelClass(SimulationDa
ta.java:171)
        ... 4 more
.
.
.
... can anyone help me....!!!!?

**Comment by miquelmartin** [comment]
That's odd. A couple questions:
1. Can you give me your java version and wether it's Oracle, OpenJDK or something else?
2. What's your command line to run Siafu?
3. What example simulation are you using? 
4. Have you made any modifications to the simulation?
5. Are you loading the simulation as a jar, or as a bunch of classes?

I'm just trying to reproduce your problem, see if I can figure out what the problem is. 
Thx!

**Comment by aven1** [comment]
java version : 
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
.
.
.
my command line :  
C:\Users\Dante\Siafu-master\target\Siafu-1.0.6-SNAPSHOT>java -Xmx512m -jar Siafu
.jar
Using configuration at C:\Users\Dante\AppData\Roaming\Siafu\config.xml
Creating the command listener.
Listening for external commands.
Starting Siafu...
.
.
.
this error happened in all simulation example that exist in source file...!
.
.
.
i don't have any change to configuration...!
.
.
.
I run it as .jar ...
.
.
.
Thx for your notice...

**Comment by miquelmartin** [comment]
Alright, this is not good. I have reproduced the conditions in your system, except I'm running it on a linux box. Still, I am not getting the same error as you.

My java is 1.8.0_20 but I do not expect that to be an issue. What I need is to get a hold of a Windows 8.1, I'll try tomorrow. In the meantime, has anyone else here had any similar issues on Win8.1?
